### ISSUE TITLE
Installing Error

### ISSUE THREAD

**Issue by abdullahsaurus** [fonol/anki-random-sprites#1]
When using the code on Ankiweb to install this add-on into Anki, it brings up an error saying that it doesn't recognise this as a valid download.
I tried installing it manually from github and this error message appeared
![image](https://user-images.githubusercontent.com/58623134/89552080-97b5d880-d803-11ea-9887-3caa98ac572f.png)

**Comment by fonol** [comment]
Hi, what Anki version do you use?

**Comment by abdullahsaurus** [comment]
Version 2.1.19 (3c8690ae)
Python 3.8.0 Qt 5.14.0 PyQt 5.13.2

**Comment by fonol** [comment]
Hi, as the add-on pages states, you need an Anki version >= 2.1.22 for it.

**Comment by abdullahsaurus** [comment]
Appreciate it, I assumed Anki automatically updated itself. It works now!
