### ISSUE TITLE
How to reduce the size of the sprites?

### ISSUE THREAD

**Issue by Asmedeus998** [fonol/anki-random-sprites#2]
hello there I been trying to scale the image but I really confused about it. I not very knowledge about javascript I hope you can guide me here.
Below are the example image that show up:
![Capture](https://user-images.githubusercontent.com/60872999/97532972-60b22600-19f2-11eb-82de-971d311dccad.PNG)

I thought when I click '-' and saved it, will reduce the size but it back to it original size.

is there anyway to reduce the size of that?

many thanks.

**Comment by fonol** [comment]
Hi, not at the moment I fear. The +- buttons only change the size so you can save the image with a different size, but they do not influence the size of the generated images. I will try to change that if I should update this add-on again.

There is a workaround using CSS you can do in the mean-time:
You could add the following style to your cards where you use the add-on:

`#px_canvas { zoom: 0.8; }`

You can change the value there to your liking.
0.8 -> 80% of original size
